### ISSUE TITLE
HTML5 Support

### ISSUE THREAD

**Issue by ljmf00** [vigiloproject/vigilo#9]
# TODO
- [x] Update HTML Tag's:
    - [x] **center** to **p style="text-align:right"** ;
    - [x] **center** to **div id="center"** ;
    - [x] **br** tag without end bar;
    - [x] **/p** tag without start position;
    - [x] **div** without tag end .
    - [x] remove **fieldset** tag
    - [x] add **lang="en"** in **html** tag

- [ ] Create Local HTML5shiv file

**Comment by ljmf00** [comment]
# Resources
- Eclipse Debugger
- http://www.w3schools.com

**Comment by ljmf00** [comment]
# Internet Explorer 9 HTML5
``` html
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
```

**Comment by ljmf00** [comment]
## New TAG's

HTML5 offers new elements for better document structure:


| Tag	| Description |
|----------|:-------------:|
| article | Defines an article in the document |
| aside | Defines content aside from the page content |
| bdi | Defines a part of text that might be formatted in a different direction from other text |
| details | Defines additional details that the user can view or hide |
| dialog | Defines a dialog box or window |
| figcaption | Defines a caption for a "figure" tag element |
| figure | Defines self-contained content, like illustrations, diagrams, photos, code listings, etc. |
| footer | Defines a footer for the document or a section |
| header | Defines a header for the document or a section |
| main | Defines the main content of a document |
| mark | Defines marked or highlighted text |
| menuitem | Defines a command/menu item that the user can invoke from a popup menu |
| meter | Defines a scalar measurement within a known range (a gauge) |
| nav | Defines navigation links in the document |
| progress | Defines the progress of a task |
| rp | Defines what to show in browsers that do not support ruby annotations |
| rt | Defines an explanation/pronunciation of characters (for East Asian typography) |
| ruby | Defines a ruby annotation (for East Asian typography) |
| section | Defines a section in the document |
| summary | Defines a visible heading for a "details" tag element |
| time | Defines a date/time |
| wbr | Defines a possible line-break |

**Check this artice in:** http://www.w3schools.com/html/html5_new_elements.asp

**Comment by ljmf00** [comment]
Tag 	Description
<form> 	Defines an HTML form for user input
<input> 	Defines an input control
<textarea> 	Defines a multiline input control (text area)
<label> 	Defines a label for an <input> element
<fieldset> 	Groups related elements in a form
<legend> 	Defines a caption for a <fieldset> element
<select> 	Defines a drop-down list
<optgroup> 	Defines a group of related options in a drop-down list
<option> 	Defines an option in a drop-down list
<button> 	Defines a clickable button
<datalist> 	Specifies a list of pre-defined options for input controls
<keygen> 	Defines a key-pair generator field (for forms)
<output> 	Defines the result of a calculation

**Comment by ljmf00** [comment]
# Internet Explorer HTML5
``` html
<!--[if IE]>
	<meta content="true" name="MSSmartTagsPreventParsing">
    	<meta content="false" http-equiv="imagetoolbar">
    <![endif]-->
```

**Comment by ljmf00** [comment]
# NoScript JavaScript Alert

``` html
<!-- NoScript Alert -->
<noscript>
    	<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
			<span><strong>Notice: </strong> JavaScript is not enabled. <a href="http://enable-javascript.com/" class="alert-link">Please Enable JavaScript Safley</a>.</span>
		</div>
</noscript>
```

**Comment by ljmf00** [comment]
``` html
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
```

**Comment by ljmf00** [comment]
# Elements Removed in HTML5

The following HTML4 elements have been removed from HTML5:

Element 	Use instead
<acronym> 	<abbr>
<applet> 	<object>
<basefont> 	CSS
<big> 	CSS
<center> 	CSS
<dir> 	<ul>
<font> 	CSS
<frame> 	 
<frameset> 	 
<noframes> 	 
<strike> 	CSS
<tt> 	CSS
